"""
Alert Management Module

This module handles the generation and storage of safety alerts.

Responsibilities:
    - Store evidence frames when a suspicious event is detected.
    - Generate unique filenames using timestamps.
    - Prevent repeated alerts using a cooldown mechanism.
    - Display incident reports generated by the AI pipeline.

The AlertManager works at the final stage of the surveillance pipeline:

Camera
   ↓
Object Detection
   ↓
Tracking
   ↓
Behavior Analysis
   ↓
Risk Assessment
   ↓
AlertManager
   ↓
Evidence Storage + Notification

"""

import os
import cv2
import time
from datetime import datetime


class AlertManager:
    """
    Controls alert generation and evidence storage.

    The AlertManager receives incident reports from the risk analysis
    module and saves the corresponding video frame as evidence.

    A cooldown mechanism is implemented to avoid generating multiple
    alerts for the same continuous event.

    Attributes:
        folder (str):
            Directory where alert images are stored.

        last_alert_time (float):
            Timestamp of the most recent generated alert.

        cooldown (int):
            Minimum time interval between two alerts in seconds.
    """


    def __init__(self):
        """
        Initialize the AlertManager.

        Creates the alert storage directory and initializes
        the alert cooldown timer.
        """

        self.folder = "data/alerts"

        # Create alert directory if it does not exist
        os.makedirs(
            self.folder,
            exist_ok=True
        )

        # Store time of previous alert
        self.last_alert_time = 0

        # Prevent repeated alerts within this duration
        self.cooldown = 10


    def send(
        self,
        frame,
        report
    ):
        """
        Generate and store a safety alert.

        The function checks the cooldown period before creating
        a new alert. If sufficient time has passed, it saves the
        current frame and displays the incident report.

        Args:
            frame (numpy.ndarray):
                Current camera frame associated with the incident.

            report (str):
                Generated description of the detected event.

        Returns:
            None

        Workflow:
            1. Check alert cooldown.
            2. Update alert timestamp.
            3. Save incident frame.
            4. Display alert information.
        """

        current_time = time.time()


        # Avoid repeated alerts for the same ongoing incident
        if (
            current_time -
            self.last_alert_time
            < self.cooldown
        ):
            return


        # Update last alert generation time
        self.last_alert_time = current_time


        # Generate unique filename
        timestamp = datetime.now().strftime(
            "%Y%m%d_%H%M%S"
        )


        image_path = os.path.join(
            self.folder,
            f"alert_{timestamp}.jpg"
        )


        # Save frame as incident evidence
        cv2.imwrite(
            image_path,
            frame
        )


        # Display alert information
        print("\n ALERT")
        print(report)
        print("Saved:", image_path)