"""
Alert Management Module

This module handles the generation and storage of safety alerts.

Responsibilities:
    - Create an alert directory if it does not exist.
    - Save the video frame associated with a detected event.
    - Display the generated incident report.
    - Provide the path of the saved evidence image.

The AlertManager is used at the final stage of the surveillance pipeline:

Camera
   ↓
Detection
   ↓
Behavior Analysis
   ↓
Risk Assessment
   ↓
AlertManager
   ↓
Stored Evidence + Alert Report
"""

import os
import cv2
from datetime import datetime


class AlertManager:
    """
    Manages safety alerts generated by the surveillance system.

    The AlertManager stores visual evidence of detected incidents
    and outputs the corresponding incident report.

    Attributes:
        folder (str):
            Directory where alert images are stored.
    """

    def __init__(self):
        """
        Initialize the AlertManager.

        Creates the alert storage directory if it does not already exist.
        """

        self.folder = "data/alerts"

        os.makedirs(
            self.folder,
            exist_ok=True
        )


    def send(self, frame, report):
        """
        Generate and save an alert.

        This function saves the current video frame as evidence and
        prints the generated incident report.

        Args:
            frame (numpy.ndarray):
                Current video frame captured from the surveillance stream.

            report (str):
                Generated description of the detected incident.

        Returns:
            None

        Example:
            AlertManager.send(
                frame,
                "High risk activity detected near entrance"
            )
        """

        # Generate unique timestamp for the alert image filename
        timestamp = datetime.now().strftime(
            "%Y%m%d_%H%M%S"
        )


        # Create path for storing alert evidence image
        image_path = os.path.join(
            self.folder,
            f"alert_{timestamp}.jpg"
        )


        # Save the frame captured during the incident
        cv2.imwrite(
            image_path,
            frame
        )


        # Display alert information
        print("\n= ALERT =")

        print(report)

        print(
            "Saved:",
            image_path
        )
