"""
API Data Schema Module

This module defines the data models used for API request and response validation.

Pydantic models ensure that data exchanged through the FastAPI application
follows a predefined structure with proper type validation.

Role in System:

    AI Processing Pipeline
            |
            ↓
    Incident Analysis
            |
            ↓
    IncidentResponse Schema
            |
            ↓
    FastAPI API Response
            |
            ↓
    Dashboard / Client Application
"""

from pydantic import BaseModel


class IncidentResponse(BaseModel):
    """
    Represents the response generated after analyzing a safety incident.

    This schema contains the final output of the risk assessment and
    reporting pipeline.

    Attributes:
        score (int):
            Numerical risk score assigned to the detected incident.

        level (str):
            Risk severity category such as LOW, MEDIUM, HIGH, or CRITICAL.

        report (str):
            Human-readable incident description generated by the
            reporting module.
    """

    score: int
    level: str
    report: str